config/routes.rb
Rails.application.routes.draw do

  	resources :contents

  	devise_for :users
  	
  	devise_scope :user do
	  get '/users', to: 'devise/registrations#new'
	  get '/users/password', to: 'devise/passwords#new'
	end

	root 'contents#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    user ||= User.new
    if user.admin?
        can :manage, :all
    else
        can :update, Content, user_id: user.id
        can :destroy, Content, user_id: user.id
        
        can :read, Content
        can :create, Content
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :contents, dependent: :destroy
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :title, presence:true
  validates :body, presence:true
  validates :description, presence:true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness:true

  has_many :contents, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    	def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :password, :current_password)}
        end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  load_and_authorize_resource
  
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]

  def index
    if params[:category].blank?
      @contents = Content.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
    end
  end

  def show
  end

  def new
    @content = current_user.contents.build
  end

  def edit
  end

  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_content
      @content = Content.find(params[:id])
    end

    def content_params
      params.require(:content).permit(:title, :body, :description,:user_id, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= simple_form_for(@content) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title,label:false,placeholder:'Title' %>
    <%= f.input :body,label:false,placeholder:'Body' %>
    <%= f.association :category,label:false,prompt:'Category' %>
    <%= f.input :description,label:false,placeholder:'Description', input_html: {rows: 8}%>
    <%= f.association :user ,as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,"Submit",:class=>"btn btn-sm btn-primary ml-0" %>
    <%= link_to "Cancel", root_path, :class=>"btn btn-sm btn-info"%>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div class="row" style="margin-top: 10vh">
	<div class="col-md-12">
		<div class="card mb-2">
			<div class="card-body">
				<h4 class="text-center pt-1 pb-3">Edit article</h4>
				<%= render 'form', content: @content %>
			</div>
		</div>
	</div>
</div>

app/views/contents/index.html.erb
<div class="row pt-2">
  <div class="col-md-9">
      <div class="row">
        <% @contents.each do |content| %>
          <div class="col-md-12">
            <div class="card mb-2">
              <div class="card-body">
                <h4><%= content.title %>
                  <div class="badge badge-primary">
                    <%= content.category.name %>
                  </div>
                </h4>
                <p><%= content.body %></p>
                <p class="text-muted">Published on <%= content.created_at.strftime("%B, %d, %Y") %> by 
                  <% if content.user.name? %>
                    <%= content.user.name %>
                  <% else %>
                    <%= content.user.email %>
                  <% end %>
                </p>
                <%= link_to "See Full Content", content %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </div>
  <div class="col-md-3">
    <div class="list-group">
      <% Category.all.each do |category| %>
        <button type="button" class="list-group-item list-group-item-action">
          <%= link_to category.name,contents_path(category: category.name) %>
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/contents/new.html.erb
<div class="row" style="margin-top: 10vh">
	<div class="col-md-12">
		<div class="card mb-2">
			<div class="card-body">
				<h4 class="text-center pt-1 pb-3">Add new article</h4>
				<%= render 'form', content: @content %>
			</div>
		</div>
	</div>
</div>

app/views/contents/show.html.erb
<div class="row">
  <div class="col-md-12" style="margin-top: 5vh">
    <div class="card">
      <div class="card-body">
        <h4><strong><%= @content.title %></strong></h4>
    <hr class="my-1">
    <p>From Wikipedia, the free encyclopedia</p>
    <p class="text-justify"><%= @content.description.html_safe %></p>

    <%= link_to "Back", contents_path %>
    
    <% if can? :update, @content %>
    |
        <%= link_to "Edit",edit_content_path  %>
    <% end %>
    
    <% if can? :destroy, @content %>
    |
        <%= link_to "Delete",content_path,method: :delete,data:{confirm:'Are you sure?'} %>
    <% end %>
    
    <% if user_signed_in? %>
    |
        <% if can? :create, @content %>
            <%= link_to "New Article",new_content_path %>
        <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikipedia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('icon.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.11.0/css/mdb.min.css" rel="stylesheet">
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  </head>
  <body>
    <%= render 'shared/alert' %>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.11.0/js/mdb.min.js"></script>
  </body>
</html>

app/views/shared/_alert.html.erb
<% if flash[:notice] %>
    <div id="notice_wrapper">
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert"><i class="far fa-times-circle"></i></button>
            <%= flash[:notice] %>
        </div>
    </div>
<% elsif flash[:error] %>
    <div id="notice_wrapper">
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert"><i class="far fa-times-circle"></i></button>
            <%= flash[:error] %>
        </div>
    </div>
<% elsif flash[:alert] %>
    <div id="notice_wrapper">
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert"><i class="far fa-times-circle"></i></button>
            <%= flash[:alert] %>
        </div>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light #fafafa grey lighten-5 scrolling-navbar">
    <div class="container">
      <%= link_to root_path,:class=>"navbar-brand" do %>
        <i class="fab fa-wikipedia-w"></i> Rails-Wikipedia
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "All Articles", root_path, :class=>"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "New Article", new_content_path, :class=>"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Account", edit_user_registration_path, :class=>"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "Log-out", destroy_user_session_path,method: :delete, :class=>"nav-link"%>
            </li>
          <% else %>
            <li class="nav-item mr-1">
              <div class="nav-link"><i class="fas fa-user-alt"></i> Not logged in</div>
              
            </li>
            <li class="nav-item">
              <%= link_to "Create account", new_user_registration_path, :class=>"nav-link"%>
            </li>
            
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, :class=>"nav-link"%>
            </li>
            
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>